### ISSUE TITLE
Hardcoded scaling of imported animations is not useful in all cases

### ISSUE THREAD

**Issue by mayasombra** [SE2Dev/io_anim_seanim#10]
https://github.com/SE2Dev/io_anim_seanim/blob/master/import_seanim.py#L11 adjusts the incoming seanim data to match models for the CoD case. However, importing models from other programs, that scaling operation might not be necessary. For OW model imports, that team has basically deployed a hack to undo this hack.

https://github.com/overtools/OWLib/blob/master/TankLib/ExportFormats/SEAnim.cs#L121

However, that hack causes problems because now the seanim and model files the OW tools produce are no longer self-consistent, which causes problems for people using other graphics packages.

Since this library is used for a variety of import cases, it'd be nice if it exposed a scaling option so CoD users could specify 1/2.54 and get the current behavior, and OW users could specify 1.0 and revert their scaling hack.

**Comment by SE2Dev** [comment]
The next version of the plugin (which will be released sometime after the stable version of Blender 2.8x), is going to be dropping the scale constant anyway - as it seems to introduce more problems than it solves.

(See https://github.com/SE2Dev/io_anim_seanim/pull/6)

**Comment by mayasombra** [comment]
Awesome. Sounds like the OW folks should be prepared to make the corresponding fix when you release your new plugin!
