### ISSUE TITLE
Import>SEanim not showing up

### ISSUE THREAD

**Issue by Smurfson** [SE2Dev/io_anim_seanim#13]
When trying to import an SEanim, the option to import is not visible within the file > import menu. The plugin shows up fine within the preferences tab, just won't show up when trying to add an animation to a skeleton.

**Comment by SE2Dev** [comment]
Are you sure you *enabled* the plugin via the preference menu?

**Comment by Smurfson** [comment]
NVM fixed it! was because I was in 2.8 and not 2.79. Just downloaded the 2.79 version of the SEModel plugin and everything worked perfectly fine :-)

Sorry about that!

**Comment by SE2Dev** [comment]
A 2.8x version is coming soon!
