### ISSUE TITLE
Weird bone scaling

### ISSUE THREAD

**Issue by a1steaksa** [SE2Dev/io_anim_seanim#15]
When importing viewmodel animations from MW2 onto viewhands models, I get weird scaling issues.
![lidd8uw](https://user-images.githubusercontent.com/8369707/61076786-a8b6cf00-a3e2-11e9-8464-b00d0d68e526.png)

These issues do not appear on weapon models, only hands and arms.  The animation plays fine, but is warped in this way.

Is there a fix for this?

**Comment by SE2Dev** [comment]
I don't own MW2 - but I'm fairly certain that this is the issue:

> This issue is caused by a combination of Blender-CoD being outdated, and the legacy scale constant (which was originally present to ensure compatibility with Blender-CoD), which was removed in io_seanim v0.3.8.
> 
> Originally all animations were scaled by down by 2.54 because Wraith internally converted the units to cm whereas Blender-CoD uses inches; this feature was removed in io_seanim v0.3.8 to ensure proper compatibility with other games, but Blender-CoD hasn't been updated yet.
> 
> The current solution is to set the model scale to 2.54 when import XMODEL_EXPORT files in Blender-CoD (as seen below).
> 
> ![image](https://user-images.githubusercontent.com/5873790/56519486-2d92fa80-6510-11e9-9074-4a72a010c807.png)

**Comment by A1steaksa** [comment]
I'm just looking through my open issues for some classic account cleaning and I just years later saw this reply.  Thanks for the info!  I suspect I'll want this when I get the itch to mess with those models again.  Thanks!
