### ISSUE TITLE
Skeleton (refpose) get distorted after seanim is applied.

### ISSUE THREAD

**Issue by FifouBE** [SE2Dev/io_anim_seanim#17]
Hey, 

thanks for the update! I was trying it by charging a simple animation into blender with your program. (I'm using the refpose.smd and binding it with armature deform to the mesh) but it seems like it gets crazy and distorted after I apply the seanim file onto the skeleton (refpose)..
![image](https://user-images.githubusercontent.com/30213090/62841515-5569c200-bca9-11e9-8cf9-d3d7870e1046.png)

I saw that in edit mode : 
![image](https://user-images.githubusercontent.com/30213090/62841526-7fbb7f80-bca9-11e9-8ffa-5dbbd43eab5c.png)

And here is the base model and skeleton without anim

![image](https://user-images.githubusercontent.com/30213090/62841529-8f3ac880-bca9-11e9-865b-05b596aa3eef.png)

Don't know if that helps, but it seems it's the scale being weird! 

Thanks again :)

**Comment by SE2Dev** [comment]
When importing the model, try scaling it by 2.54 - the default scale constant was changed in this version, so you might need to do that for legacy anims.

**Comment by FifouBE** [comment]
It doesn't seems to fix it unfortunately, model is still being distorted. I just scaled the mesh, not the refpose one..

**Comment by SE2Dev** [comment]
Can you send me the source files you're using, so I can check them out when I get the chance?

**Comment by FifouBE** [comment]
It seems to work by scaling everything by 2.54!

Nevermind on my other response, false manipulation on blender ;)

Thanks!

**Comment by SE2Dev** [comment]
Excellent, cheers!
