### ISSUE TITLE
Using Blender 2.79b has Import > Seanim greyed out.

### ISSUE THREAD

**Issue by KyButler** [SE2Dev/io_anim_seanim#21]
Using -> https://github.com/SE2Dev/io_anim_seanim/tree/6a420cb470c46a6a6309cf2214e1c48be00f8e42 as the enabled addon, I'm greeted with this. Please let me know what I can provide to help diagnose the issue. 
![image](https://user-images.githubusercontent.com/12141121/66545198-6e4ef200-eaf7-11e9-8ad5-8d18ad369975.png)

**Comment by SE2Dev** [comment]
You need to select an armature, or model that is linked to an armature to import the animation onto. Otherwise the menu option will be disabled.

**Comment by KyButler** [comment]
Oh. Yeah, you're right.
