### ISSUE TITLE
bugged CoD4 animation

### ISSUE THREAD

**Issue by Tasijjj** [SE2Dev/io_anim_seanim#3]
Hey,
I've tried to import "stand-jump-land" animation from Call of Duty 4 to Blender and I've got this weird rig movement that is almost unrecognizable. I've used the newest Wraith exporter tool to export the animation and tried exporting from non-patched and patched versions of CoD4.

Any help would be appreciated.

![blow - kopija](https://user-images.githubusercontent.com/32816558/34910555-1e8fb3ae-f8b8-11e7-8bdb-1f752dabb7df.gif)
![blow](https://user-images.githubusercontent.com/32816558/34910557-29b0061c-f8b8-11e7-82f6-80531b26e350.gif)

**Comment by SE2Dev** [comment]
Which are the names of the anim and model that you are using?

**Comment by Tasijjj** [comment]
Model: body_mp_usmc_woodland_assault
Anim: pb_standjump_land

Note that I've used CoDEmanX Blender add-on for the model (with armature) import, so the problem could be there as well.

**Comment by SE2Dev** [comment]
Which version of Blender-CoD?

**Comment by Tasijjj** [comment]
I downloaded Blender-CoD from this link: https://github.com/CoDEmanX/blender-cod

That would be very kind of you, if you could do that.
You can send it to this mail: mod2asd@outlook.com or name your preferred method.

**Comment by SE2Dev** [comment]
[blender-cod@0.6.0~wip.zip](https://github.com/SE2Dev/io_anim_seanim/files/1633222/blender-cod.0.6.0.wip.zip)

**Comment by Tasijjj** [comment]
It works!
I'm not really sure how, but it does. For example, I don't really understand how the mesh is parented to the armature. I am not to big of a Blender expert btw.

Thank you very much!

![anim](https://user-images.githubusercontent.com/32816558/34994020-8b91daf6-fad2-11e7-8240-e8a673d5130d.gif)
