### ISSUE TITLE
SEanim additve animations are not currenly supported Version0.4.1 on Blender 2.90.1

### ISSUE THREAD

**Issue by GamingNexus1** [SE2Dev/io_anim_seanim#30]
what can i do to fix the error?

**Comment by SE2Dev** [comment]
There's nothing either of us can do right now. They have a lot of fundamental differences from other types of animations, and I have no reference for how they're supposed to look in-editor.

It's not possible to implement support for them at this time.

**Comment by SE2Dev** [comment]
Duplicate of #8
