### ISSUE TITLE
Issue when trying to enable addon.

### ISSUE THREAD

**Issue by psychoella** [SE2Dev/io_anim_seanim#43]
Hi, I get this error in the console when trying to enable the addon. It says...

**Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'io_anim_seanim-0'**

Can anyone help me at all? 

Thanks in advance.

**Comment by SE2Dev** [comment]
That's my fault, I made a mistake when creating the release archive. Try downloading 0.4.2 again, it should work now.

**Comment by psychoella** [comment]
Don't worry at all, thank you so much I really appreciate your help. Thank you for the tool by the way, it's been so useful to me.
